### PR TITLE
Creating slightly better filenames.

### PR DESCRIPTION
**Pull request by danvuquoc**

### CODE REVIEW

**Comment by raldenhoven** [comment]
Hey I love the improvement... this extension was never ment to go main stream, and I actualy hope Spotify fixes it soon, so I'm a bit reluctant to merge. Basicly Spotify is awesome, I think I made my point no need to hurt them.

**Comment by Dygear** [comment]
What was your point? That they have a shockingly large security hole in their web player implementation? Did you contact Spotify before you released your code?

**Comment by raldenhoven** [comment]
I submitted their contact form on monday... so they already had some time, they still have not responded in any way.

**Comment by Djamana** [comment]
@raldenhoven  'Freeing' some music from the Spotify bubble doesn't hurts anyone. 
Security hole - is that really one? Let's be honest do you really need that kind of 'security'?
Who needs a DRM? The only ppl that comes to my mind are the ones from the content-mafia.
So am I Sony? ...am I the GEMA? 

Help to keep this security as lax as possible. Its just there to fulfill/satisfy some legal requirements.

**Pull request closed without merging**
